### ISSUE TITLE
Is there any way to customize the time gutter on each row (not just the gutter header?)

### ISSUE THREAD

**Issue by ehahn9** [jquense/react-big-calendar#1614]
#### Do you want to request a _feature_ or report a _bug_?
Feature (or question?)

#### What's the current behavior?
Each time is displayed like this:

![image](https://user-images.githubusercontent.com/299134/76709747-702c6b00-66be-11ea-9671-e093c73a63dd.png)

#### What's the expected behavior?
I'd like to customize the look of this rather dramatically (heat maps, etc.). I don't see any `components` prop which allows me to customize this -- correct?

*apologizes if this is already present - I couldn't find it.*

**Comment by KotamanMeOplo** [comment]
I have the same question/issue

**Comment by Tilteee** [comment]
some news?

**Comment by KeiShadow** [comment]
You can only change style of gutter, for example like this:
const customSlotPropGetter = () => {
		return {
			className: 'slot',
			style: {
				minHeight: '10vh',
			},
		};
	};

This will change height of ceel on left side, and all of cell in talbe, except top header will stay same.
In calendar component you have to add this slotPropGetter={customSlotPropGetter}

**Comment by namvu97** [comment]
I have same issue.

**Comment by cDurhamZP** [comment]
I would also like to see more component overrides

**Comment by gmgk93** [comment]
Anyone able to customize the TimeGutter ? not just the header ?

**Comment by nkaramarko** [comment]
I would also like the possibility to change the data displayed in the gutter. for example to show weeks in Month view instead of time

**Comment by cutterbl** [comment]
@nkaramarko I'm confused. The Month view doesn't show a TimeGutter. What is it you're trying to do exactly?

**Comment by nkaramarko** [comment]
@cutterbl i would like to show the gutter on the Month view but instead of time show the week number in there.

**Comment by cutterbl** [comment]
@nkaramarko But, there is no gutter on the Month View. Only on the Day and Week Views. You might need to build some kind of custom view to do what you're looking to do.

**Comment by nkaramarko** [comment]
@cutterbl i know, but there should be a gutter in month view and there should be a possibility to customize it. :)
would be a nice feature to add

**Comment by eduardolbruno** [comment]
I have the same issue. 
I need to customize the TimeGutter

**Comment by cutterbl** [comment]
There are only four ways to change the TimeGutter, outside of the TimeGutterHeader. As mentioned earlier, you can use the [slotGroupPropGetter](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--slot-group-prop-getter) or [slotPropGetter](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--slot-prop-getter) to make basic styling changes. You can use the [timeGutterFormat](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--formats-time-gutter-format) to adjust how the time is displayed. And you can apply a custom [TimeGutterWrapper](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--formats-time-gutter-format)

**Comment by eduardolbruno** [comment]
Is it possible to do something like this, but on the Agenda View? 
Basically I need to change the styling of the time shown on the "Time" column (insert inside a div, like a children and include some styling on the div)

![image](https://github.com/jquense/react-big-calendar/assets/111282091/c22fe347-eb91-4baf-8e64-f646e1d0b0fa)

**Comment by eduardolbruno** [comment]
> Is it possible to do something like this, but on the Agenda View? Basically I need to change the styling of the time shown on the "Time" column (insert inside a div, like a children and include some styling on the div)
> 
> ![image](https://private-user-images.githubusercontent.com/111282091/305523239-c22fe347-eb91-4baf-8e64-f646e1d0b0fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMDg2MDcsIm5iZiI6MTcwODEwODMwNywicGF0aCI6Ii8xMTEyODIwOTEvMzA1NTIzMjM5LWMyMmZlMzQ3LWViOTEtNGJhZi04ZTY0LWY2NDZlMWQwYjBmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQxODMxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzFkMDI5NjU4MTQ3ZmU4NmU0ZDUxYjRlNTY1MjA5YzE1ODFiOTI2ODQwMjFlZDZjYzE3YTA4NGNhYzUzZjQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eFBmxVXcEOOrUWghZ6kkwoJqYftMQAMJbbvPaKI9aE8)

Ok, so I solved overriding the original css. I know its not the best approach, but it helps me a lot on what Im working rn. 
I leave it here in case someone is looking for a similar styling in the UI (_take in consideration, this only works using Agenda view_).

```scss

 /* detects full time on Time column */
.rbc-agenda-view table.rbc-agenda-table .rbc-agenda-time-cell > span  
{
    background: #E0E0E0 !important;
    border-radius: 16px !important;
    padding: 3px 12px 3px 12px !important;
    font-size: 14px !important;
    font-weight: 400 !important;    
}

/* detects '<<' on <<all day>> placeholder */
.rbc-agenda-view table.rbc-agenda-table .rbc-agenda-time-cell > span::before  
{
    display: none !important;
}

/* detects '>>' on <<all day>> placeholder */
.rbc-agenda-view table.rbc-agenda-table .rbc-agenda-time-cell > span::after  
{
    display: none !important;
}
``` 

![image](https://github.com/jquense/react-big-calendar/assets/111282091/e0287f9d-d7e8-4db3-97df-a6b396aaf6e4)
