### ISSUE TITLE
Toolbar Wrap Behaviour < 768px

### ISSUE THREAD

**Issue by kimfucious** [jquense/react-big-calendar#1699]
#### Do you want to request a _feature_ or report a _bug_?
This more of a suggestion to improve the UX, but some might call it a UX bug?
#### What's the current behavior?
On screen widths < 768px, with the height is set at 600px for example, the tool bar wraps and looks pretty awkward until around 350px, depending on the month, when it will wrap enough to put the button groups and the label on separate rows.![image](https://user-images.githubusercontent.com/26792769/87172691-d0df5380-c2fe-11ea-9713-d2e9323bbd00.png)
I've found that if you start (mobile first) with:
```scss
.rbc-toolbar {
  flex-direction: row;
  align-items: center;
}
.rbc-toolbar-label {
  font-weight: 400;
  margin-top: 0.5rem;
  margin-bottom: 0.5rem;
}
```
And then change the `.rbc-toolbar` to have `flex-direction: row;` above when >= 768px width.

With that, you don't have that staggered look between ~350 and 768.

I've made these mods locally, using SCSS in the project I'm working on, but it might be nice to have this baked in.

That is unless someone else has a better idea.

#### What's the expected behavior?
I would expect that the toolbar doesn't wrap and look all wonky under 768px

Great product, BTW!  I haven't loved anything so much since Yup!
