### ISSUE TITLE
Changing drag handle icons?

### ISSUE THREAD

**Issue by shrihari-prakash** [jquense/react-big-calendar#2698]
### Clear and concise description of the problem

First of all, wonderful library! It was super flexible for most of my needs, and I really appreciated it!

I managed to style most parts of the calendar except for the drag handles. Those seem a little out of place with respect to the rest of the UI. Is there a possibility to send my own icon or modify it via JS? I've been trying to find the icon on the source code, but I couldn't and the icon div also seems empty.

![Screenshot 2024-12-18 at 11 18 11](https://github.com/user-attachments/assets/6f8cd8cc-0ee8-499f-b275-08c15b2d836a)

### Suggested solution

It would be good to have a prop to accept drag handle icon.

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples/index.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by shrihari-prakash** [comment]
Ok nevermind, I just had to add the below css:

```css
.rbc-addons-dnd-resizable {
  position: relative;
}
.rbc-addons-dnd-resize-ew-anchor {
  top: 3px !important;
}
.rbc-addons-dnd-resize-ew-icon, .rbc-addons-dnd-resize-ns-icon {
  background-color: hsla(var(--primary) / 50%);
  border: none !important;
  border-radius: 4px;
}
.rbc-addons-dnd-resize-ew-icon {
  width: 3px;
  height: 12px !important;
}
.rbc-addons-dnd-resize-ns-icon {
  height: 3px;
  width: 12px !important;
}
```
